# Description keywords that trigger automatic exclusion.
# Any single match in the job description body = skip the posting.
EXCLUSION_KEYWORDS = [
    "llm architecture",
    "fine-tuning",
    "fine tuning",
    "rag pipeline",
    "rag pipelines",
    "retrieval-augmented generation",
    "ml engineering",
    "machine learning engineering",
    "hands-on coding",
    "hands on coding",
    "python required",
    "proficiency in python",
    "tensorflow",
    "pytorch",
    "building models",
    "train models",
    "training models",
    "production code",
    "write production",
    "deep learning",
    "neural network architecture",
    "transformer architecture",
    "langchain",
    "llamaindex",
    "llama index",
    "vector database",
    "embedding models",
    "model deployment",
    "mlops",
    "ml ops",
    "cuda",
    "gpu cluster",
]

# Companies whose core product IS an AI model or AI platform.
# Matching is case-insensitive substring — catches "OpenAI" inside "OpenAI Inc".
AI_NATIVE_COMPANIES = [
    "openai",
    "anthropic",
    "cohere",
    "mistral",
    "mistral ai",
    "inflection",
    "inflection ai",
    "stability ai",
    "stabilityai",
    "midjourney",
    "runway ml",
    "runwayml",
    "character.ai",
    "character ai",
    "adept ai",
    "adept",
    "together ai",
    "togetherai",
    "perplexity",
    "perplexity ai",
    "you.com",
    "deepmind",
    "google deepmind",
    "hugging face",
    "huggingface",
    "scale ai",
    "labelbox",
    "weights & biases",
    "wandb",
    "anyscale",
    "modal labs",
    "modal.com",
    "replicate",
    "pinecone",
    "weaviate",
    "qdrant",
    "chroma",
    "milvus",
    "zilliz",
    "langchain",
    "llamaindex",
    "xai",  # Elon's X.AI
    "grok ai",
    "aleph alpha",
    "writer.com",
    "jasper ai",
    "copy.ai",
    "jasper",
    "tome",
    "synthesis ai",
    "nvidia ai",  # For AI-product divisions specifically
    "ai21 labs",
    "ai21",
    "cerebras",
    "sambanova",
    "groq",  # The inference chip/cloud company
]
