# Exact target titles — used for fuzzy matching against scraped results.
# The fuzzy threshold is 85/100 (rapidfuzz WRatio).
TARGET_TITLES = [
    # AI Leadership
    "Head of AI",
    "Head of AI Strategy",
    "Head of AI Strategy & Transformation",
    "Head of Artificial Intelligence",
    "VP of AI",
    "VP AI",
    "VP AI Strategy",
    "VP AI Enablement",
    "VP AI Transformation",
    "Vice President of AI",
    "Vice President AI Strategy",
    "Director of AI Transformation",
    "Director AI Strategy",
    "Director of AI",
    "Director of Artificial Intelligence",
    "Chief AI Officer",
    "CAIO",
    "GM of AI",
    "General Manager AI",
    "General Manager of AI",
    "GM Artificial Intelligence",
    "Head of AI Products",
    "Head of AI Enablement",
    "Director of AI Enablement",
    "VP of AI Products",
    "VP of Artificial Intelligence",
    "Head of AI Adoption",
    "Head of Enterprise AI",
    "Director of Enterprise AI",
    "VP of Enterprise AI",
    "Chief of AI",
    "Chief AI Enablement Officer",
    "AI Program Director",
    "Head of AI Programs",
    "Director of AI Programs",
    "AI Center of Excellence Lead",
    "Head of AI CoE",
    "Director of AI CoE",
    "Director of AI & Automation",
    "Director of AI and Automation",

    # Digital & Business Transformation
    "Director of Digital Transformation",
    "VP of Digital Transformation",
    "Vice President of Digital Transformation",
    "Head of Digital Transformation",
    "Director Digital Transformation",
    "VP Digital Transformation",
    "Head Digital Transformation",
    "VP of Business Transformation",
    "Director of Business Transformation",
    "Head of Business Transformation",
    "Head of Technology Transformation",
    "Director of Technology Transformation",

    # Automation & Innovation
    "Head of Intelligent Automation",
    "Director of Intelligent Automation",
    "VP of Intelligent Automation",
    "VP of Innovation",
    "Director of Innovation",
    "Head of Innovation",
]

# If any of these strings appear in the scraped title it's an automatic
# include (case-insensitive substring match, runs before fuzzy matching).
TITLE_INCLUDE_KEYWORDS = [
    "head of ai",
    "vp of ai",
    "vp ai",
    "director of ai",
    "director ai",
    "chief ai",
    "chief of ai",
    "caio",
    "gm of ai",
    "gm ai",
    "general manager ai",
    "head of artificial intelligence",
    "vp artificial intelligence",
    "ai enablement",
    "ai adoption",
    "enterprise ai",
    "ai program",
    "ai center of excellence",
    "ai coe",
    "ai & automation",
    "ai and automation",
    "digital transformation",
    "business transformation",
    "technology transformation",
    "intelligent automation",
    "head of innovation",
    "vp of innovation",
    "director of innovation",
]

# Fuzzy match score threshold (0-100).
TITLE_FUZZY_THRESHOLD = 82

# Short search terms submitted to job boards (a subset of TARGET_TITLES
# chosen to maximise recall without excessive API calls).
_SEARCH_TERMS = [
    "Head of AI",
    "VP of AI",
    "VP AI Strategy",
    "Director of AI Transformation",
    "Chief AI Officer",
    "GM of AI",
    "Head of AI Enablement",
    "Head of Enterprise AI",
    "AI Program Director",
    "AI Center of Excellence",
    "Director of AI & Automation",
    "Head of Digital Transformation",
    "VP of Digital Transformation",
    "Director of Digital Transformation",
    "VP of Business Transformation",
    "Head of Intelligent Automation",
    "VP of Innovation",
    "Director of Innovation",
]
